require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::VenuesController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # Venue. As you add validations to Venue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    attributes_for(:venue)
  end

  describe "GET index" do
    it "raises" do
      expect { get :index, params: {} }.to raise_error(ActionController::UrlGenerationError)
    end
  end

  describe "GET show" do
    it "raises" do
      expect { get :show, params: {:id => 0 } }.to raise_error(ActionController::UrlGenerationError)
    end
  end

  describe "GET new" do
    it "assigns a new venue as @venue" do
      get :new, params: { :location_id => create(:location).to_param }
      assigns(:venue).should be_a_new(Venue)
    end
  end

  describe "GET edit" do
    it "assigns the requested venue as @venue" do
      venue = create(:venue)
      get :edit, params: {:id => venue.to_param}
      assigns(:venue).should eq(venue)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Venue" do
        expect {
          post :create, params: { :location_id => create(:location).to_param,
                          :venue => valid_attributes }
        }.to change(Venue, :count).by(1)
      end

      it "assigns a newly created venue as @venue" do
        post :create, params: { :location_id => create(:location).to_param,
                        :venue => valid_attributes }
        assigns(:venue).should be_a(Venue)
        assigns(:venue).should be_persisted
      end

      it "redirects to the locations_list" do
        post :create, params: { :location_id => create(:location).to_param,
                        :venue => valid_attributes }
        response.should redirect_to(admin_locations_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved venue as @venue" do
        # Trigger the behavior that occurs when invalid params are submitted
        location = create(:location)
        allow_any_instance_of(Venue).to receive(:save).and_return(false)
        post :create, params: { :location_id => location.to_param,
                        :venue => { "name" => "" } }
        assigns(:venue).should be_a_new(Venue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        location = create(:location)
        post :create, params: { :location_id => location.to_param,
                        :venue => { "name" => "" } }
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested venue" do
        venue = create(:venue)
        # Assuming there are no other venues in the database, this
        # specifies that the Venue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        allow_any_instance_of(Venue).to receive(:update_attributes).
                                        with(PermittedParams.new("name" => "MyString"))
        put :update, params: {:id => venue.to_param, :venue => { "name" => "MyString" }}
      end

      it "assigns the requested venue as @venue" do
        venue = create(:venue)
        put :update, params: {:id => venue.to_param, :venue => valid_attributes}
        assigns(:venue).should eq(venue)
      end

      it "redirects to the locations list" do
        venue = create(:venue)
        put :update, params: {:id => venue.to_param, :venue => valid_attributes}
        response.should redirect_to(admin_locations_url)
      end
    end

    describe "with invalid params" do
      it "assigns the venue as @venue" do
        venue = create(:venue)
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Venue).to receive(:save).and_return(false)
        put :update, params: {:id => venue.to_param, :venue => { "name" => "" }}
        assigns(:venue).should eq(venue)
      end

      it "re-renders the 'edit' template" do
        venue = create(:venue)
        # Trigger the behavior that occurs when invalid params are submitted
        put :update, params: {:id => venue.to_param, :venue => { "name" => "" }}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested venue" do
      venue = create(:venue)
      expect {
        delete :destroy, params: {:id => venue.to_param}
      }.to change(Venue, :count).by(-1)
    end

    it "redirects to the locations list" do
      venue = create(:venue)
      delete :destroy, params: {:id => venue.to_param}
      response.should redirect_to(admin_locations_url)
    end
  end

end
