require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FilmsController do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # Film. As you add validations to Film, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    attributes_for(:film)
  end

  describe "GET index" do
    it "assigns all films as @films and festival as @festival" do
      film = create(:film)
      get :index, { festival_id: film.festival.to_param }
      assigns(:films).should eq([film])
      assigns(:festival).should eq(film.festival)
    end
  end

  describe "GET show" do
    it "assigns the film as @film and festival as @festival" do
      film = create(:film)
      get :show, {:id => film.to_param}
      assigns(:film).should eq(film)
      assigns(:festival).should eq(film.festival)
    end
  end

  describe "GET new" do
    it "assigns a new film as @film and festival as @festival" do
      festival = create(:festival)
      get :new, { festival_id: festival.to_param }
      assigns(:film).should be_a_new(Film)
      assigns(:festival).should eq(festival)
    end
  end

  describe "GET edit" do
    it "assigns the requested film as @film and festival as @festival" do
      film = create(:film)
      get :edit, {:id => film.to_param}
      assigns(:film).should eq(film)
      assigns(:festival).should eq(film.festival)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Film" do
        expect {
          post :create, { festival_id: create(:festival).to_param,
                          film: valid_attributes }
        }.to change(Film, :count).by(1)
      end

      it "assigns a newly created film as @film" do
        post :create, { festival_id: create(:festival).to_param,
                        film: valid_attributes }
        assigns(:film).should be_a(Film)
        assigns(:film).should be_persisted
      end

      it "redirects to the festival films list" do
        festival = create(:festival)
        post :create, { festival_id: festival,
                        film: valid_attributes }
        response.should redirect_to(festival_films_url(festival))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved film as @film " +
         "and festival as @festival" do
        # Trigger the behavior that occurs when invalid params are submitted
        festival = create(:festival)
        Film.any_instance.stub(:save).and_return(false)
        post :create, { festival_id: festival.to_param,
                        film: { "name" => "" } }
        assigns(:film).should be_a_new(Film)
        assigns(:festival).should eq(festival)
      end

      it "re-renders the 'new' template" do
        festival = create(:festival)
        # Trigger the behavior that occurs when invalid params are submitted
        Film.any_instance.stub(:save).and_return(false)
        post :create, { festival_id: festival.to_param,
                        film: { "name" => "" } }
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested film" do
        film = create(:film)
        # Assuming there are no other films in the database, this
        # specifies that the Film created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Film.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => film.to_param, :film => { "name" => "MyString" }}
      end

      it "assigns the requested film as @film and festival as @festival" do
        film = create(:film)
        put :update, {:id => film.to_param, :film => valid_attributes}
        assigns(:film).should eq(film)
        assigns(:festival).should eq(film.festival)
      end

      it "redirects to the festival films list" do
        film = create(:film)
        put :update, {:id => film.to_param, :film => valid_attributes}
        response.should redirect_to(festival_films_url(film.festival))
      end
    end

    describe "with invalid params" do
      it "assigns the film as @film and festival as @festival" do
        film = create(:film)
        # Trigger the behavior that occurs when invalid params are submitted
        Film.any_instance.stub(:save).and_return(false)
        put :update, {:id => film.to_param, :film => { "name" => "" }}
        assigns(:film).should eq(film)
        assigns(:festival).should eq(film.festival)
      end

      it "re-renders the 'edit' template" do
        film = create(:film)
        # Trigger the behavior that occurs when invalid params are submitted
        Film.any_instance.stub(:save).and_return(false)
        put :update, {:id => film.to_param, :film => { "name" => "" }}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested film" do
      film = create(:film)
      expect {
        delete :destroy, {:id => film.to_param}
      }.to change(Film, :count).by(-1)
    end

    it "redirects to the festival films list" do
      film = create(:film)
      delete :destroy, {:id => film.to_param}
      response.should redirect_to(festival_films_url(film.festival))
    end
  end
end
